Part6
lockatme/lockatme-specifications pull request #9
Opened 2018-01-14 19:12 UTC by PLsergent

Part 6 almost finish
Il manque juste 3 images et il faut régler le problème des figures

2018-01-14 20:29 UTC, sweenu requested changes
Super boulot!! Mais pas mal de petites choses par ci, par là. Il faut également que tu enlèves le dossier .latex de ta PR.

2018-01-14 20:29 UTC, sweenu commented on specifications/main.tex
> +\usepackage[french]{babel}
Le package babel est déjà présent (plus bas), tu peux donc supprimer cette ligne.

2018-01-14 20:29 UTC, sweenu commented on specifications/part3.tex
>  \begin{figure}[h]\label{fig:scrum}
Enlève le \label sur cette ligne please.

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +projet sera certainement upload sur pip. Il pourra donc utiliser la commande
Il sera upload sur PyPI (Python Package Index) qui est le repository pour les programmes Python. pip est l'outil en ligne de commande qui permet d'interagire avec le PyPI.

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +installé le package pip de python :
"le package pip :" de python est en trop.

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +Pour installer le logiciel lockatme, les utilisateurs auront deux options. Le
Tu parle de l'utilisateur au singulier sur la ligne suivante donc je te propose de le mettre au singulier ici aussi:
l'utilisateur aura deux options

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +Sinon il pourra tout simplement cloner le projet depuis GitHub en réalisant la
Plus simplement: "Sinon il pourra compiler le projet lui-même avec les commandes suivantes:
$ git clone ...
$ cd lockatme
$ make install

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +Le dossier comprendra un fichier exécutable en Python que l'utilisateur pourra
Non, ça sera utlisable comme n'importe quel programme juste avec _lockatme_. C'est a ça que ça sert d'installer le programme.

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +le fichier exécutable \emph{lockatme.py} sera présent dans le dossier du logiciel. Son
voir commentaire au dessus

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +fichier \emph{config.py}), si le déverrouillage échoue l'utilisateur sera invité à
Juste: "le fichier de configuration" parce qu'on ne sait pas comment il va s'appeler mais surement pas config.py car ce ne sera pas un fichier Python.

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +fichier \emph{password.py}. En cas d'absence de photos
Tu peux enlever la phrase qui parle du mot de passe, parce qu'il ne sera pas stocké dans un fichier password.py, ça c'est sûr.

2018-01-14 20:29 UTC, sweenu commented on specifications/part6.tex
> +  ~/.config/i3/$ atom config
Haha atom. Autant mettre vim parce que c'est installer de base en général.

2018-01-14 20:29 UTC, Sweenu commented on specifications/part6.tex
> +dans le VII.\\
Du coup nan.

2018-01-14 20:29 UTC, Sweenu commented on specifications/part6.tex
> +  /etc/$ mkdir acpi
Il faut installer acpid et ça va créer les répertoires /etc/acpi et /etc/acpi/events de lui-même.

2018-01-14 20:29 UTC, Sweenu commented on specifications/part6.tex
> +  /etc/acpi/events/$ atom lid
atom encore mdr

2018-01-14 20:29 UTC, Sweenu commented on specifications/part6.tex
> +Nous avons par la suite trouvé une autre bibliothèque bien plus avancé :
je dirais "plus haut niveau" au lieu de "bien plus avancé"

2018-01-14 20:29 UTC, Sweenu commented on specifications/part6.tex
> +  \begin{verbatim}
tu peux utiliser listing comme tu l'as fait plus haut avec Python comme language, comme ça on aura du syntax highlighting.

2018-01-16 20:01 UTC, PLsergent commented
je pense que ya eu un problème du coup avec le rebase et j'ai rechangé des trucs sur part 1,2,3... pour le \newpage donc la je sais pas comment faire,

2018-01-16 20:45 UTC, sweenu requested changes

2018-01-16 20:45 UTC, sweenu commented on specifications/part6.tex
> +\begin{lstlisting}[language=bash]
python, pas bash :P

2018-01-16 21:30 UTC, sweenu approved these changes

2018-01-16 21:31 UTC, merged